name: Daily Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:     # manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Chrome & Chromedriver versions
      run: |
        chromium-browser --version
        chromedriver --version

    - name: Run scraping scripts
      run: |
        python main.py

    - name: Commit and push changes if any
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *.json
        git diff --cached --quiet || (git commit -m "🔄 Daily data update $(date +'%Y-%m-%d')" && git push)
